#!/bin/bash
ip tuntap add mode tap tap0
ip link set dev tap0 up
echo 1 > /proc/sys/net/ipv6/conf/all/forwarding
sysctl net.ipv6.conf.tap0.accept_dad=0
ip -6 addr add fe80::10 dev tap0
ip -6 addr add fe80::20 dev tap0
ip -6 addr add fe80::30 dev tap0
ip -6 addr add fe80::40 dev tap0
ip -6 addr add fe80::50 dev tap0
exit

